List<Map<String, dynamic>> categoriesJson = [
  {
    "id": "Espadin",
    "title": "Espadin",
    'category_id': "Mezcal",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Tobala",
    'category_id': "Mezcal",
    "title": "Tobala",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Tobasiche",
    'category_id': "Mezcal",
    "title": "Tobasiche",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Barril",
    'category_id': "Mezcal",
    "title": "Barril",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Alto",
    'category_id': "Mezcal",
    "title": "Alto",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Cupreata",
    'category_id': "Mezcal",
    "title": "Cupreata",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Tequilana",
    'category_id': "Mezcal",
    "title": "Tequilana",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Azul",
    'category_id': "Mezcal",
    "title": "Azul",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Pechuga",
    'category_id': "Mezcal",
    "title": "Pechuga",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Tepeztate",
    'category_id': "Mezcal",
    "title": "Tepeztate",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Mexicano",
    'category_id': "Mezcal",
    "title": "Mexicano",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Salmiana",
    'category_id': "Mezcal",
    "title": "Salmiana",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Ensamble",
    'category_id': "Mezcal",
    "title": "Ensamble",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Bicuixe",
    'category_id': "Mezcal",
    "title": "Bicuixe",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Madrecuishe",
    'category_id': "Mezcal",
    "title": "Madrecuishe",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Arroqueno",
    'category_id': "Mezcal",
    "title": "Arroqueno",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
  {
    "id": "Karwinskii",
    'category_id': "Mezcal",
    "title": "Karwinskii",
    "color1": "#DE4001",
    "color2": "#FFEEE7",
  },
];
