// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfB9FhtuAXzjtJW4B2MFfhxualNgghwUI',
    appId: '1:584611625768:web:6e0e0e0f1bbaf5de326e1d',
    messagingSenderId: '584611625768',
    projectId: 'maguey-all-day-app',
    authDomain: 'maguey-all-day-app.firebaseapp.com',
    storageBucket: 'maguey-all-day-app.appspot.com',
    measurementId: 'G-8ZS3JSWCGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgzG_QH5pkgcO9rLU5LAcUaLUkoshT_U',
    appId: '1:584611625768:android:d8713a514ec8ac61326e1d',
    messagingSenderId: '584611625768',
    projectId: 'maguey-all-day-app',
    storageBucket: 'maguey-all-day-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-uiQXRxc0nups5ufXfQflhFRz7x0Cfo',
    appId: '1:584611625768:ios:429b244b9929d02d326e1d',
    messagingSenderId: '584611625768',
    projectId: 'maguey-all-day-app',
    storageBucket: 'maguey-all-day-app.appspot.com',
    androidClientId: '584611625768-0f8fs0lmiahkbeh2s0ou7ljbq10ummpq.apps.googleusercontent.com',
    iosClientId: '584611625768-ltj3c0m6iu774gddomneu6vldm49n713.apps.googleusercontent.com',
    iosBundleId: 'com.magueyallday.magueyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-uiQXRxc0nups5ufXfQflhFRz7x0Cfo',
    appId: '1:584611625768:ios:2034aaff17918fb1326e1d',
    messagingSenderId: '584611625768',
    projectId: 'maguey-all-day-app',
    storageBucket: 'maguey-all-day-app.appspot.com',
    androidClientId: '584611625768-0f8fs0lmiahkbeh2s0ou7ljbq10ummpq.apps.googleusercontent.com',
    iosClientId: '584611625768-haphfukfq7lho41s9dehqltfc6nufl11.apps.googleusercontent.com',
    iosBundleId: 'com.magueyallday.magueyapp.magueyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfB9FhtuAXzjtJW4B2MFfhxualNgghwUI',
    appId: '1:584611625768:web:6e0e0e0f1bbaf5de326e1d',
    messagingSenderId: '584611625768',
    projectId: 'maguey-all-day-app',
    authDomain: 'maguey-all-day-app.firebaseapp.com',
    storageBucket: 'maguey-all-day-app.appspot.com',
    measurementId: 'G-8ZS3JSWCGT',
  );
}
